version: "3.8"
name: tapico

services:
  topica-server:
    image: ghcr.io/snazzieslab/topica.server:nightly
    ports:
      - 8080:8080
    environment:
      SecretKey: "YourSecretfrsfwafawfwafwfafwfawftKey"
      DbType: InMemory
      DbConnectionString:
    volumes:
      - ./auth.config.json:/app/auth.config.json
  topica-ui:
    image: ghcr.io/snazzieslab/topica.ui:nightly
    ports:
      - 3000:8080
