version: "3.8"
name: tapico

services:
  topica-server:
    image: ghcr.io/snazzieslab/topica:nightly
    ports:
      - 8080:8080
    environment:
      DbType: InMemory
      DbConnectionString:
    volumes:
      - ./auth.config.json:/app/auth.config.json
