version: '3.4'

services:
  events:
    image: ${DOCKER_REGISTRY-}events
    build:
      context: .
      dockerfile: Events/Dockerfile

  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    restart: always
    command: start --user test --pass test file:/data/database.db
    ports:
      - 8000:8000
    volumes:
      - ./data:/data