/* tslint:disable */
/* eslint-disable */
/**
 * Events, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Message } from './Message';
import {
    MessageFromJSON,
    MessageFromJSONTyped,
    MessageToJSON,
} from './Message';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    uid?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Event
     */
    createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    description?: string | null;
    /**
     * 
     * @type {{ [key: string]: Message; }}
     * @memberof Event
     */
    history?: { [key: string]: Message; } | null;
}

/**
 * Check if a given object implements the Event interface.
 */
export function instanceOfEvent(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EventFromJSON(json: any): Event {
    return EventFromJSONTyped(json, false);
}

export function EventFromJSONTyped(json: any, ignoreDiscriminator: boolean): Event {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'uid': !exists(json, 'uid') ? undefined : json['uid'],
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
        'description': !exists(json, 'description') ? undefined : json['description'],
        'history': !exists(json, 'history') ? undefined : (json['history'] === null ? null : mapValues(json['history'], MessageFromJSON)),
    };
}

export function EventToJSON(value?: Event | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'uid': value.uid,
        'createdOn': value.createdOn === undefined ? undefined : (value.createdOn.toISOString()),
        'description': value.description,
        'history': value.history === undefined ? undefined : (value.history === null ? null : mapValues(value.history, MessageToJSON)),
    };
}

