/*
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Topica.Client.Model;
using Topica.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Topica.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Entry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Entry
        //private Entry instance;

        public EntryTests()
        {
            // TODO uncomment below to create an instance of Entry
            //instance = new Entry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Entry
        /// </summary>
        [Fact]
        public void EntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" Entry
            //Assert.IsType<Entry>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'EntryId'
        /// </summary>
        [Fact]
        public void EntryIdTest()
        {
            // TODO unit test for the property 'EntryId'
        }
    }
}
