/*
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Topica.Client.Model;
using Topica.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Topica.Client.Test.Model
{
    /// <summary>
    ///  Class for testing LoginModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoginModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoginModel
        //private LoginModel instance;

        public LoginModelTests()
        {
            // TODO uncomment below to create an instance of LoginModel
            //instance = new LoginModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoginModel
        /// </summary>
        [Fact]
        public void LoginModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" LoginModel
            //Assert.IsType<LoginModel>(instance);
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
