/*
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Topica.Client.Model;
using Topica.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Topica.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TopicMetaPaginatedResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TopicMetaPaginatedResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TopicMetaPaginatedResponse
        //private TopicMetaPaginatedResponse instance;

        public TopicMetaPaginatedResponseTests()
        {
            // TODO uncomment below to create an instance of TopicMetaPaginatedResponse
            //instance = new TopicMetaPaginatedResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TopicMetaPaginatedResponse
        /// </summary>
        [Fact]
        public void TopicMetaPaginatedResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" TopicMetaPaginatedResponse
            //Assert.IsType<TopicMetaPaginatedResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }

        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
