/*
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Topica.Client.Model;
using Topica.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Topica.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TopicMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TopicMetaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TopicMeta
        //private TopicMeta instance;

        public TopicMetaTests()
        {
            // TODO uncomment below to create an instance of TopicMeta
            //instance = new TopicMeta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TopicMeta
        /// </summary>
        [Fact]
        public void TopicMetaInstanceTest()
        {
            // TODO uncomment below to test "IsType" TopicMeta
            //Assert.IsType<TopicMeta>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Fact]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
    }
}
