/*
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Topica.Client.Client;
using Topica.Client.Api;

namespace Topica.Client.Test.Api
{
    /// <summary>
    ///  Class for testing MessagesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MessagesApiTests : IDisposable
    {
        private MessagesApi instance;

        public MessagesApiTests()
        {
            instance = new MessagesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MessagesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MessagesApi
            //Assert.IsType<MessagesApi>(instance);
        }

        /// <summary>
        /// Test AddMessage
        /// </summary>
        [Fact]
        public void AddMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? topicId = null;
            //string? body = null;
            //var response = instance.AddMessage(topicId, body);
            //Assert.IsType<string>(response);
        }
    }
}
