/*
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Topica.Client.Client;
using Topica.Client.Api;
// uncomment below to import models
//using Topica.Client.Model;

namespace Topica.Client.Test.Api
{
    /// <summary>
    ///  Class for testing TopicsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TopicsApiTests : IDisposable
    {
        private TopicsApi instance;

        public TopicsApiTests()
        {
            instance = new TopicsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TopicsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TopicsApi
            //Assert.IsType<TopicsApi>(instance);
        }

        /// <summary>
        /// Test CreateTopic
        /// </summary>
        [Fact]
        public void CreateTopicTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? topicId = null;
            //var response = instance.CreateTopic(topicId);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test DeleteMessage
        /// </summary>
        [Fact]
        public void DeleteMessageTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string topicId = null;
            //Guid messageId = null;
            //instance.DeleteMessage(topicId, messageId);
        }

        /// <summary>
        /// Test DeleteTopic
        /// </summary>
        [Fact]
        public void DeleteTopicTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string topicId = null;
            //instance.DeleteTopic(topicId);
        }

        /// <summary>
        /// Test GetTopic
        /// </summary>
        [Fact]
        public void GetTopicTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string topicId = null;
            //var response = instance.GetTopic(topicId);
            //Assert.IsType<Topic>(response);
        }

        /// <summary>
        /// Test GetTopics
        /// </summary>
        [Fact]
        public void GetTopicsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? page = null;
            //int? pageSize = null;
            //string? search = null;
            //var response = instance.GetTopics(page, pageSize, search);
            //Assert.IsType<TopicMetaPaginatedResponse>(response);
        }

        /// <summary>
        /// Test GetTotal
        /// </summary>
        [Fact]
        public void GetTotalTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetTotal();
            //Assert.IsType<int>(response);
        }
    }
}
