/*
 * Events, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "dateTimeOffset")]
    pub date_time_offset: String,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "eventUid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub event_uid: Option<Option<String>>,
}

impl Message {
    pub fn new(date_time_offset: String, content: String) -> Message {
        Message {
            date_time_offset,
            content,
            event_uid: None,
        }
    }
}


