/* tslint:disable */
/* eslint-disable */
/**
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Entry
 */
export interface Entry {
    /**
     * 
     * @type {Date}
     * @memberof Entry
     */
    createdOn?: Date;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Entry
     */
    entryId?: string;
}

/**
 * Check if a given object implements the Entry interface.
 */
export function instanceOfEntry(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EntryFromJSON(json: any): Entry {
    return EntryFromJSONTyped(json, false);
}

export function EntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entry {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
        'content': !exists(json, 'content') ? undefined : json['content'],
        'entryId': !exists(json, 'entryId') ? undefined : json['entryId'],
    };
}

export function EntryToJSON(value?: Entry | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'createdOn': value.createdOn === undefined ? undefined : (value.createdOn.toISOString()),
        'content': value.content,
        'entryId': value.entryId,
    };
}

