/* tslint:disable */
/* eslint-disable */
/**
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginModel
 */
export interface LoginModel {
    /**
     * 
     * @type {string}
     * @memberof LoginModel
     */
    username?: string | null;
    /**
     * 
     * @type {string}
     * @memberof LoginModel
     */
    password?: string | null;
}

/**
 * Check if a given object implements the LoginModel interface.
 */
export function instanceOfLoginModel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginModelFromJSON(json: any): LoginModel {
    return LoginModelFromJSONTyped(json, false);
}

export function LoginModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function LoginModelToJSON(value?: LoginModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
    };
}

