/* tslint:disable */
/* eslint-disable */
/**
 * Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TopicMeta
 */
export interface TopicMeta {
    /**
     * 
     * @type {string}
     * @memberof TopicMeta
     */
    id?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TopicMeta
     */
    createdOn?: Date;
}

/**
 * Check if a given object implements the TopicMeta interface.
 */
export function instanceOfTopicMeta(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TopicMetaFromJSON(json: any): TopicMeta {
    return TopicMetaFromJSONTyped(json, false);
}

export function TopicMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TopicMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdOn': !exists(json, 'createdOn') ? undefined : (new Date(json['createdOn'])),
    };
}

export function TopicMetaToJSON(value?: TopicMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdOn': value.createdOn === undefined ? undefined : (value.createdOn.toISOString()),
    };
}

