/*
Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package topicaclient

import (
	"encoding/json"
	"time"
)

// checks if the TopicMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopicMeta{}

// TopicMeta struct for TopicMeta
type TopicMeta struct {
	Id NullableString `json:"id,omitempty"`
	CreatedOn *time.Time `json:"createdOn,omitempty"`
}

// NewTopicMeta instantiates a new TopicMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopicMeta() *TopicMeta {
	this := TopicMeta{}
	return &this
}

// NewTopicMetaWithDefaults instantiates a new TopicMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopicMetaWithDefaults() *TopicMeta {
	this := TopicMeta{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TopicMeta) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TopicMeta) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *TopicMeta) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *TopicMeta) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *TopicMeta) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *TopicMeta) UnsetId() {
	o.Id.Unset()
}

// GetCreatedOn returns the CreatedOn field value if set, zero value otherwise.
func (o *TopicMeta) GetCreatedOn() time.Time {
	if o == nil || IsNil(o.CreatedOn) {
		var ret time.Time
		return ret
	}
	return *o.CreatedOn
}

// GetCreatedOnOk returns a tuple with the CreatedOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicMeta) GetCreatedOnOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedOn) {
		return nil, false
	}
	return o.CreatedOn, true
}

// HasCreatedOn returns a boolean if a field has been set.
func (o *TopicMeta) HasCreatedOn() bool {
	if o != nil && !IsNil(o.CreatedOn) {
		return true
	}

	return false
}

// SetCreatedOn gets a reference to the given time.Time and assigns it to the CreatedOn field.
func (o *TopicMeta) SetCreatedOn(v time.Time) {
	o.CreatedOn = &v
}

func (o TopicMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopicMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.CreatedOn) {
		toSerialize["createdOn"] = o.CreatedOn
	}
	return toSerialize, nil
}

type NullableTopicMeta struct {
	value *TopicMeta
	isSet bool
}

func (v NullableTopicMeta) Get() *TopicMeta {
	return v.value
}

func (v *NullableTopicMeta) Set(val *TopicMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableTopicMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableTopicMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopicMeta(val *TopicMeta) *NullableTopicMeta {
	return &NullableTopicMeta{value: val, isSet: true}
}

func (v NullableTopicMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopicMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


