/*
Topica.Server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package topicaclient

import (
	"encoding/json"
)

// checks if the TopicMetaPaginatedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TopicMetaPaginatedResponse{}

// TopicMetaPaginatedResponse struct for TopicMetaPaginatedResponse
type TopicMetaPaginatedResponse struct {
	Data []TopicMeta `json:"data,omitempty"`
	Page *int32 `json:"page,omitempty"`
	PageSize *int32 `json:"pageSize,omitempty"`
	Total *int32 `json:"total,omitempty"`
}

// NewTopicMetaPaginatedResponse instantiates a new TopicMetaPaginatedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTopicMetaPaginatedResponse() *TopicMetaPaginatedResponse {
	this := TopicMetaPaginatedResponse{}
	return &this
}

// NewTopicMetaPaginatedResponseWithDefaults instantiates a new TopicMetaPaginatedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTopicMetaPaginatedResponseWithDefaults() *TopicMetaPaginatedResponse {
	this := TopicMetaPaginatedResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TopicMetaPaginatedResponse) GetData() []TopicMeta {
	if o == nil {
		var ret []TopicMeta
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TopicMetaPaginatedResponse) GetDataOk() ([]TopicMeta, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *TopicMetaPaginatedResponse) HasData() bool {
	if o != nil && IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []TopicMeta and assigns it to the Data field.
func (o *TopicMetaPaginatedResponse) SetData(v []TopicMeta) {
	o.Data = v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *TopicMetaPaginatedResponse) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicMetaPaginatedResponse) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *TopicMetaPaginatedResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *TopicMetaPaginatedResponse) SetPage(v int32) {
	o.Page = &v
}

// GetPageSize returns the PageSize field value if set, zero value otherwise.
func (o *TopicMetaPaginatedResponse) GetPageSize() int32 {
	if o == nil || IsNil(o.PageSize) {
		var ret int32
		return ret
	}
	return *o.PageSize
}

// GetPageSizeOk returns a tuple with the PageSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicMetaPaginatedResponse) GetPageSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.PageSize) {
		return nil, false
	}
	return o.PageSize, true
}

// HasPageSize returns a boolean if a field has been set.
func (o *TopicMetaPaginatedResponse) HasPageSize() bool {
	if o != nil && !IsNil(o.PageSize) {
		return true
	}

	return false
}

// SetPageSize gets a reference to the given int32 and assigns it to the PageSize field.
func (o *TopicMetaPaginatedResponse) SetPageSize(v int32) {
	o.PageSize = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TopicMetaPaginatedResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TopicMetaPaginatedResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TopicMetaPaginatedResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *TopicMetaPaginatedResponse) SetTotal(v int32) {
	o.Total = &v
}

func (o TopicMetaPaginatedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TopicMetaPaginatedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PageSize) {
		toSerialize["pageSize"] = o.PageSize
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableTopicMetaPaginatedResponse struct {
	value *TopicMetaPaginatedResponse
	isSet bool
}

func (v NullableTopicMetaPaginatedResponse) Get() *TopicMetaPaginatedResponse {
	return v.value
}

func (v *NullableTopicMetaPaginatedResponse) Set(val *TopicMetaPaginatedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTopicMetaPaginatedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTopicMetaPaginatedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTopicMetaPaginatedResponse(val *TopicMetaPaginatedResponse) *NullableTopicMetaPaginatedResponse {
	return &NullableTopicMetaPaginatedResponse{value: val, isSet: true}
}

func (v NullableTopicMetaPaginatedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTopicMetaPaginatedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


