version: "3.4"

services:
  topica.server:
    image: ${DOCKER_REGISTRY-}topica.server
    container_name: topica.server
    ports:
      - 8080:8080
    build:
      context: ./Topica.Server/Topica.Server
      dockerfile: Dockerfile
  topica.ui:
    image: ${DOCKER_REGISTRY-}topica.ui
    container_name: topica.ui
    ports:
      - 3001:80
    build:
      context: .
      dockerfile: Dockerfile.UI
